// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://face.wezhuiyi.com",
            "email": "mushaolei@wezhuiyi.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "post": {
                "description": "创建用户",
                "tags": [
                    "User"
                ],
                "summary": "CreateUser",
                "operationId": "CreateUser",
                "parameters": [
                    {
                        "description": "body请求",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/user.CreateRESP"
                        }
                    },
                    "500": {
                        "description": "失败"
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "获取用户信息",
                "tags": [
                    "User"
                ],
                "summary": "GetUser",
                "operationId": "GetUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/user.UserInfo"
                        }
                    },
                    "500": {
                        "description": "失败"
                    }
                }
            }
        }
    },
    "definitions": {
        "user.CreateBody": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "user.CreateRESP": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "user.UserInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户id",
                    "type": "string"
                },
                "name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.1.3",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Blueprint New Face Web API",
	Description:      "Swagger API for Face Project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
